# typed: strict
# frozen_string_literal: true

# Generated by scripts/release/package_metadata.py. Do not edit.
cask "devknx-app" do
  version "0.1.0"
  sha256 "a03089da552279ba4afe42a0a7227d37789ee6b2e0569fe5b2f6d6e1e683dc8e"

  url "https://github.com/metaneutrons/devknx/releases/download/v0.1.0/devknx-v0.1.0-aarch64-apple-darwin.app.zip"
  name "devknx"
  desc "KNX monitor with CLI, TUI, GUI, REST and MCP"
  homepage "https://github.com/metaneutrons/devknx"

  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :monterey

  app "devknx.app"

  caveats <<~EOS
    The command line tool is a separate package:
      brew install metaneutrons/tap/devknx
  EOS
end
