# Generated by scripts/release/package-metadata.sh. Do not edit by hand.
cask "devserial-app" do
  version "0.1.12"
  sha256 "504fa0da28816c718e1ddd561fac9cd970f707e32c4ce7963d884728e2fd2364"

  url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.1.12/devserial-0.1.12-macos-universal.app.zip"
  name "devserial"
  desc "MCP server bridging serial hardware to LLMs via SQLite-backed buffer"
  homepage "https://github.com/metaneutrons/devserial"

  # Stanza order and the bare symbol are what `brew style` demands; it
  # autocorrects anything else, and a generated file cannot be autocorrected.
  depends_on macos: :big_sur

  app "devserial.app"

  zap trash: [
    "~/Library/Application Support/devserial",
    "~/Library/Caches/devserial",
    "~/Library/Preferences/com.metaneutrons.devserial.plist",
    "~/Library/Saved Application State/com.metaneutrons.devserial.savedState",
  ]

  # The CLI of the same program comes from the formula. Naming it here means
  # `brew info` says so instead of leaving people to find out.
  caveats <<~EOS
    The command line tool is a separate package:
      brew install metaneutrons/tap/devserial
  EOS
end
