# typed: strict
# frozen_string_literal: true

# Generated by scripts/release/package-metadata.sh. Do not edit by hand.
cask "devserial-app" do
  version "0.2.6"
  sha256 "7c986cfa8c5f47223d74a539bbf124443d9404c3b57217f1984ddb3c1f494e8a"

  url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.2.6/devserial-0.2.6-macos-universal.app.zip"
  name "devserial"
  desc "Serial terminal with SQLite-buffered output and CLI, TUI, GUI, REST and MCP"
  homepage "https://github.com/metaneutrons/devserial"

  auto_updates true
  depends_on macos: :monterey

  app "devserial.app"

  zap trash: [
    "~/Library/Application Support/devserial",
    "~/Library/Caches/devserial",
    "~/Library/Preferences/com.metaneutrons.devserial.plist",
    "~/Library/Saved Application State/com.metaneutrons.devserial.savedState",
  ]

  # The CLI of the same program comes from the formula. Naming it here means
  # `brew info` says so instead of leaving people to find out.
  caveats <<~EOS
    The command line tool is a separate package:
      brew install metaneutrons/tap/devserial
  EOS
end
