# Generated by scripts/release/package-metadata.sh. Do not edit by hand.
cask "devserial-app" do
  version "0.2.1"
  sha256 "d2efd6ea2568655d5ddd779f634308e73cbc4b9a905e682a1075a536f3c9bfb7"

  url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.2.1/devserial-0.2.1-macos-universal.app.zip"
  name "devserial"
  desc "Serial terminal with SQLite-buffered output and CLI, TUI, GUI, REST and MCP"
  homepage "https://github.com/metaneutrons/devserial"

  # Stanza order and the bare symbol are what `brew style` demands; it
  # autocorrects anything else, and a generated file cannot be autocorrected.
  depends_on macos: :big_sur

  app "devserial.app"

  zap trash: [
    "~/Library/Application Support/devserial",
    "~/Library/Caches/devserial",
    "~/Library/Preferences/com.metaneutrons.devserial.plist",
    "~/Library/Saved Application State/com.metaneutrons.devserial.savedState",
  ]

  # The CLI of the same program comes from the formula. Naming it here means
  # `brew info` says so instead of leaving people to find out.
  caveats <<~EOS
    The command line tool is a separate package:
      brew install metaneutrons/tap/devserial
  EOS
end
