# typed: strict
# frozen_string_literal: true

# Generated by scripts/release/package_metadata.py. Do not edit.
class Devknx < Formula
  desc "KNX monitor with CLI, TUI, GUI, REST and MCP"
  homepage "https://github.com/metaneutrons/devknx"
  license "GPL-3.0-only"

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/metaneutrons/devknx/releases/download/v0.1.0/devknx-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "f79af79b0e45196a71b6073fa147a21100df7b1fd0e2480d020dfc4cf4941ee1"
    end
  end

  on_linux do
    depends_on "libx11"
    depends_on "libxcb"
    depends_on "libxcursor"
    depends_on "libxi"
    depends_on "libxkbcommon"
    depends_on "mesa"
    depends_on "wayland"
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/devknx/releases/download/v0.1.0/devknx-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "62b4c5d81a83d2fae4ee80ad6f7271c9a3dd6aabc9ae1c3ea5ad9ca2dc447965"
    else
      url "https://github.com/metaneutrons/devknx/releases/download/v0.1.0/devknx-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ead1f060e667f01325a8977ec676de8caadc0dcfeecbdf65627ab88bba82fc67"
    end
  end

  def install
    root = Dir["devknx", "devknx-v*-*/devknx"].find { |path| File.file?(path) }
    raise "missing devknx executable" unless root

    if OS.linux?
      libexec.install root
      gui_libraries = %w[
        libx11 libxcb libxcursor libxi libxkbcommon mesa wayland
      ].map { |name| formula_opt_lib(name) }
      loader_path = "#{gui_libraries.join(":")}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
      bin.join("devknx").write_env_script libexec/"devknx", LD_LIBRARY_PATH: loader_path
    else
      bin.install root
    end
    source_root = File.dirname(root)
    doc.install File.join(source_root, "THIRD-PARTY-NOTICES.md")
    doc.install File.join(source_root, "licenses")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devknx --version")
  end
end
