# Generated by scripts/release/package-metadata.sh. Do not edit by hand.
class Devserial < Formula
  desc "MCP server bridging serial hardware to LLMs via SQLite-backed buffer"
  homepage "https://github.com/metaneutrons/devserial"
  license "GPL-3.0-or-later"
  # No explicit version: Homebrew scans it from the archive name, and
  # 'brew audit --strict' rejects the redundant declaration.

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.1.7/devserial-0.1.7-aarch64-apple-darwin.tar.gz"
      sha256 "8fd6c3a7a10c83c69b47a0d3bdb569e1a3efe55c9ff1e97afcba11db2afff4cb"
    else
      url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.1.7/devserial-0.1.7-x86_64-apple-darwin.tar.gz"
      sha256 "5cb9778ea272927c09427d871974eee49c908694ec05781d244331e3129097bf"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.1.7/devserial-0.1.7-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "5711c7df72f2640d0dcb415efb64adbcb9a1858e3296ca6fa6d58d561b59bfca"
    else
      url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.1.7/devserial-0.1.7-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1fe643cc2cfa26e230fd51bce58413dc75e89f99a1163393bc295ca64e912fd9"
    end
  end

  def install
    bin.install "devserial"
    # The binary embeds font software; its notices have to travel with it.
    doc.install "THIRD-PARTY-NOTICES.md", "licenses"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devserial --version")
    assert_match "Available Serial Hardware", shell_output("#{bin}/devserial list")
  end
end
