# Generated by scripts/release/package-metadata.sh. Do not edit by hand.
class Devserial < Formula
  desc "Serial terminal with SQLite-buffered output and CLI, TUI, GUI, REST and MCP"
  homepage "https://github.com/metaneutrons/devserial"
  license "GPL-3.0-or-later"
  # No explicit version: Homebrew scans it from the archive name, and
  # 'brew audit --strict' rejects the redundant declaration.

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.2.6/devserial-0.2.6-aarch64-apple-darwin.tar.gz"
      sha256 "c943398aca659f257721f05861540bfc5dd70f935714e7d2c6fc003cade32024"
    else
      url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.2.6/devserial-0.2.6-x86_64-apple-darwin.tar.gz"
      sha256 "86c4773e844088343934eb04d70fbda0b296feb65244ecc9d74984bfaf095767"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.2.6/devserial-0.2.6-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c965b5db3eb97bc1f5c0fa5b6171124dd28cf43552b900014e3f46a7e312ac52"
    else
      url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.2.6/devserial-0.2.6-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7bda9972feb9d39d73c4e112aad7604ce91da8743e36cc7c784d88f24e5030cf"
    end
  end

  def install
    bin.install "devserial"
    # The binary embeds font software; its notices have to travel with it.
    doc.install "THIRD-PARTY-NOTICES.md", "licenses"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devserial --version")
    assert_match "Available Serial Hardware", shell_output("#{bin}/devserial list")
  end
end
