# Generated by scripts/release/package-metadata.sh. Do not edit by hand.
class Devserial < Formula
  desc "MCP server bridging serial hardware to LLMs via SQLite-backed buffer"
  homepage "https://github.com/metaneutrons/devserial"
  license "GPL-3.0-or-later"
  # No explicit version: Homebrew scans it from the archive name, and
  # 'brew audit --strict' rejects the redundant declaration.

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.1.11/devserial-0.1.11-aarch64-apple-darwin.tar.gz"
      sha256 "ffc94516cef097cf3525531329deecdc86da9e5e4a311cb717e4795817cabd9f"
    else
      url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.1.11/devserial-0.1.11-x86_64-apple-darwin.tar.gz"
      sha256 "49adf42c4d7ecd3d88cd87ca5f8a774b7c92948e61b86e3f6fbd956133d5ae83"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.1.11/devserial-0.1.11-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "36f4b83688b83f7301e0051fe9cac44b7b3c83753238a4bc1c775cb1517cce9a"
    else
      url "https://github.com/metaneutrons/devserial/releases/download/devserial-v0.1.11/devserial-0.1.11-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9ff1da7adeaabcac54610d9bc935525f3e03d77949732683be09ef3b375c45f4"
    end
  end

  def install
    bin.install "devserial"
    # The binary embeds font software; its notices have to travel with it.
    doc.install "THIRD-PARTY-NOTICES.md", "licenses"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devserial --version")
    assert_match "Available Serial Hardware", shell_output("#{bin}/devserial list")
  end
end
