# Generated by scripts/release/generate-homebrew-formula.sh. Do not edit.
class FreebasicNg < Formula
  desc "Modern compiler for the FreeBASIC language"
  homepage "https://github.com/metaneutrons/freebasic-ng"
  license all_of: ["GPL-2.0-or-later", "LGPL-2.1-or-later"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/freebasic-ng/releases/download/v1.22.2/freebasic-ng-1.22.2-darwin-aarch64.tar.xz"
      sha256 "129a18a32a299519a86d85eefe4447cb924365585b3057f7c9270e02cc418af2"
    elsif Hardware::CPU.intel?
      url "https://github.com/metaneutrons/freebasic-ng/releases/download/v1.22.2/freebasic-ng-1.22.2-darwin-x86_64.tar.xz"
      sha256 "42b83758e0dca8045a8465de6f091a972589d65cf8221e157f7745ab6059d2c7"
    end
  end

  def install
    prefix.install Dir["*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fbc --version")
    source = testpath/"smoke.bas"
    output = testpath/"smoke"
    source.write 'Print "FreeBASIC-NG package smoke"' + "\n"
    system bin/"fbc", source, "-x", output
    assert_equal "FreeBASIC-NG package smoke\n", shell_output(output)
  end
end
