# Generated by scripts/release/generate-homebrew-formula.sh. Do not edit.
class FreebasicNg < Formula
  desc "Modern compiler for the FreeBASIC language"
  homepage "https://github.com/metaneutrons/freebasic-ng"
  license all_of: ["GPL-2.0-or-later", "LGPL-2.1-or-later"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/freebasic-ng/releases/download/v1.24.4/freebasic-ng-1.24.4-darwin-aarch64.tar.xz"
      sha256 "9bc753ecd85f8e3dd3f1e21d3315254e3b98d40f400007ec294bd403f2b83b4d"
    elsif Hardware::CPU.intel?
      url "https://github.com/metaneutrons/freebasic-ng/releases/download/v1.24.4/freebasic-ng-1.24.4-darwin-x86_64.tar.xz"
      sha256 "0cf43a8b7ac477ae3ed514079e008b8e21a2d0a239f6ead7f47dcde45e55b056"
    end
  end

  def install
    prefix.install Dir["*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fbc --version")
    source = testpath/"smoke.bas"
    output = testpath/"smoke"
    source.write 'Print "FreeBASIC-NG package smoke"' + "\n"
    system bin/"fbc", source, "-x", output
    assert_equal "FreeBASIC-NG package smoke\n", shell_output(output)
  end
end
