# Generated by scripts/release/generate-homebrew-formula.sh. Do not edit.
class FreebasicNg < Formula
  desc "Modern compiler for the FreeBASIC language"
  homepage "https://github.com/metaneutrons/freebasic-ng"
  license all_of: ["GPL-2.0-or-later", "LGPL-2.1-or-later"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/freebasic-ng/releases/download/v1.22.3/freebasic-ng-1.22.3-darwin-aarch64.tar.xz"
      sha256 "ddb4fadc376f7ba4613cd6ea025f0b6887f46c90bb9c718bf0831fb125750c00"
    elsif Hardware::CPU.intel?
      url "https://github.com/metaneutrons/freebasic-ng/releases/download/v1.22.3/freebasic-ng-1.22.3-darwin-x86_64.tar.xz"
      sha256 "82aadc871109efe953d840e3506db49a79206373e21cd1e3bf5c05aeeecae697"
    end
  end

  def install
    prefix.install Dir["*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fbc --version")
    source = testpath/"smoke.bas"
    output = testpath/"smoke"
    source.write 'Print "FreeBASIC-NG package smoke"' + "\n"
    system bin/"fbc", source, "-x", output
    assert_equal "FreeBASIC-NG package smoke\n", shell_output(output)
  end
end
