# Generated by scripts/release/generate-homebrew-formula.sh. Do not edit.
class Png2lvgl < Formula
  desc "Convert PNG images to LVGL C arrays"
  homepage "https://github.com/metaneutrons/png2lvgl"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/png2lvgl/releases/download/v0.3.9/png2lvgl-0.3.9-aarch64-apple-darwin.tar.gz"
      sha256 "70380ceb0f53145c0980b0bfb2f17f52e6a5e2ecbc63c0d3f90b571e0387debc"
    else
      url "https://github.com/metaneutrons/png2lvgl/releases/download/v0.3.9/png2lvgl-0.3.9-x86_64-apple-darwin.tar.gz"
      sha256 "ed510a245206abba769786d3e28107b77916a11d6e5b25c64d2768943a53eaf4"
    end
  end

  def install
    bin.install "png2lvgl"
    man1.install "share/man/man1/png2lvgl.1"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/png2lvgl --version")
    system bin/"png2lvgl", "--help"
  end
end
