# Generated by scripts/release/generate-homebrew-formula.sh. Do not edit.
class Png2lvgl < Formula
  desc "Convert PNG images to LVGL C arrays"
  homepage "https://github.com/metaneutrons/png2lvgl"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/png2lvgl/releases/download/v0.3.11/png2lvgl-0.3.11-aarch64-apple-darwin.tar.gz"
      sha256 "34b4d845bfe9ab005e00dc1d9b97b144765d3ceb1af2434cd7547485d6a74f8b"
    else
      url "https://github.com/metaneutrons/png2lvgl/releases/download/v0.3.11/png2lvgl-0.3.11-x86_64-apple-darwin.tar.gz"
      sha256 "410be033bf7ae0f4638ca13fab5c901b4b7576ffbd7207902e8d922dcc6c57bd"
    end
  end

  def install
    bin.install "png2lvgl"
    man1.install "share/man/man1/png2lvgl.1"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/png2lvgl --version")
    system bin/"png2lvgl", "--help"
  end
end
