# Generated by scripts/release/generate-homebrew-formula.sh. Do not edit.
class Png2lvgl < Formula
  desc "Convert PNG images to LVGL C arrays"
  homepage "https://github.com/metaneutrons/png2lvgl"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/metaneutrons/png2lvgl/releases/download/v0.3.12/png2lvgl-0.3.12-aarch64-apple-darwin.tar.gz"
      sha256 "e9e0dbc14a6fd3df1e6c32ef03c1076bd466055d196e912b752adb28b69bec39"
    else
      url "https://github.com/metaneutrons/png2lvgl/releases/download/v0.3.12/png2lvgl-0.3.12-x86_64-apple-darwin.tar.gz"
      sha256 "52a050eb324df5fad353cf650e026e513abb418b1b9e137c80ad372649e90855"
    end
  end

  def install
    bin.install "png2lvgl"
    man1.install "share/man/man1/png2lvgl.1"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/png2lvgl --version")
    system bin/"png2lvgl", "--help"
  end
end
